### ISSUE TITLE
Hyphen encoding issue in acknowledgements

### ISSUE THREAD

**Issue by nbloomf** [bor0/gidti#11]
The hyphen in the paragraph on Neil Mitchell is getting encoded as "â€Š" somehow in the preview PDF. I'm not sure what tools you're using to build the PDF, but if it's pandoc, I've had to fiddle with options to prevent "smart" conversions like this before. :) The fix might be as simple as using two hyphens instead of one.

<img width="602" alt="screen shot 2018-09-22 at 2 29 16 pm" src="https://user-images.githubusercontent.com/9310939/45921070-f7a37000-be73-11e8-90d0-53c177a3d50a.png">

**Comment by nbloomf** [comment]
I think so- I took that screenshot on the preview PDF from leanpub.

**Comment by bor0** [comment]
I'll check it. Thanks!
