### ISSUE TITLE
Chapter 3: sums are tagged unions

### ISSUE THREAD

**Issue by nbloomf** [bor0/gidti#27]
In chapter 3, definition 3 and the subsequent examples, I think it'd be helpful to note that for values of a sum type $A \mid B$ it is also possible to tell _which summand_ the value came from. I've heard sums described as _tagged unions_ for this reason -- each value has a tag that tells us which summand it belongs to. (In Haskell these are the constructors Left and Right.)

This is especially important for sums like $A \mid A$. If $a : A$ and we think of $a$ as having type $A \mid A$ as well, how do we tell which copy of $A$ $a$ came from?

**Comment by bor0** [comment]
I think your explanation in e3592d07a21209635bb5914b2b4205745ef5fd31 fixes this, thanks!
