### ISSUE TITLE
[4.1.1] Pattern matching

### ISSUE THREAD

**Issue by nbloomf** [bor0/gidti#36]
In section 4.1.1, the introduction of pattern matching is a bit out of place. Has `Z` been mentioned yet?

More generally, pattern matching really only makes sense in the context of algebraic types - it's literally a shorthand for the universal mappings on products and coproducts. I would wait to mention it until after talking about sum and product types in 4.1.2.

Edit- I see you do say more about pattern matching in 4.1.2. In that case I'd just leave it out of 4.1.1.

**Comment by bor0** [comment]
> pattern matching really only makes sense in the context of algebraic types

I agree with this but in 4.1.1 it's just a high level overview and briefly mentioned. Namely, I think the "branching" part of pattern matching is especially important to novice readers:

> The code above, depending on the input, will branch the computation to the corresponding definition.

I'll close this but feel free to do a PR with suggested changes and I'll check it :)
