### ISSUE TITLE
3.1 logical connectives commutativity

### ISSUE THREAD

**Issue by Chobbes** [bor0/gidti#5]
Why do we mention that the connectives are commutative? That seems like something you could prove later instead? Also introducing commutativity with oplus (a different operator) would be confusing to beginners, since it's not clear that this means `/\` or `\/`. If you have to have this comment, then I'd probably just include both `a /\ b = b /\ a` and `a \/ b = b \/ a` to keep things simple for the reader.

**Comment by Chobbes** [comment]
To clarify, I don't think that this comment adds anything at this stage in the book?

**Comment by bor0** [comment]
We do prove them later. I agree it's a distraction at this point 👍

**Comment by bor0** [comment]
Fixed in 729b4e20d6909b2ff9569fd5701338a76775c905.
