### ISSUE TITLE
[2.1] logic introduction truth table concerns

### ISSUE THREAD

**Issue by Chobbes** [bor0/gidti#6]
In Definition 3, the truth table:

- using top and bottom symbols for the truth table... Everything kind of blends in? I might try colouring them differently, or something?
- I also don't know that I like how the table lines up... Seems like things should be centred, not left justified?
- I think that there should be a vertical line or something after a and b, and before a /\ b to indicate that on the left a and b are assigned values, while the values on the right follow from this...
- it might even be a good idea to break this table up into several tables, one per connective. This would also let you talk a bit more about what each connective actually means.

If somebody is delving into logic for the first time, I think this section is somewhat unclear. There are no plain English definitions of the logical connectives, and instead a giant truth table that's actually fairly hard to read. The "in other words" section is just a compressed truth table with no text to motivate why these connectives behave the way they do. Even having something simple like "`and` means that both `a` _and_ `b` have to be true in order for `a /\ b` to be true" would really help to solidify this in a beginner's mind.

**Comment by bor0** [comment]
Truth tables are touched a bit in high school, but this is a valid point! :) I'll try to break up things and make them simpler.
